services:
  ollama:
    image: ollama/ollama
    deploy:
      resources:
        limits:
          memory: 16384M
    container_name: ollama
    restart: always
    environment:
      OLLAMA_KEEP_ALIVE: -1
      OLLAMA_NUM_THREADS: 8
      OLLAMA_MAX_SEQ_LEN: 1024
      OLLAMA_VERBOSE: "0"
      OLLAMA_CPU_ONLY: "1"
      OLLAMA_CACHE_IMAGE: false
      OLLAMA_DEVICE_MAPPER: cpu
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama

  webui:
    image: ghcr.io/open-webui/open-webui
    deploy:
      resources:
        limits:
          memory: 1536M
    container_name: ollama_webui
    restart: always
    ports:
      - "3003:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./ollama_webui_data:/app/backend/data
    depends_on:
      - ollama

  searxng:
    image: searxng/searxng
    deploy:
      resources:
        limits:
          memory: 512M
    container_name: searxng
    restart: unless-stopped
    ports:
      - "8888:8080"
    volumes:
      - ./searxng_config/settings.yml:/etc/searxng/settings.yml
    environment:
      - SEARXNG_HOSTNAME=localhost
    command:
      -d

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.53
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - WATCHTOWER_CLEANUP=true

volumes:
  ollama_data:
  ollama_webui_data:
  searxng_config:
  searxng_data:
